# Datamanagment

In [ ]:
from google.colab import drive
import pandas as pd
import os
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Join USA

In [ ]:
# Pfad zum Hauptordner
main_folder_path = "/content/drive/MyDrive/Projekt_VIP/Data/USA"

# Liste, um alle DataFrames zu sammeln
dfs = []

# Alle CSV-Dateien im Ordner iterieren
for file in os.listdir(main_folder_path):
    if file.endswith(".csv"):
        file_path = os.path.join(main_folder_path, file)

        # Den Dateinamen ohne Endung extrahieren
        file_name = os.path.splitext(file)[0]

        # CSV-Datei lesen
        df = pd.read_csv(file_path, sep = ";")

        # Spalte mit dem Dateinamen hinzufügen
        df["SourceFile"] = file_name

        # DataFrame zur Liste hinzufügen
        dfs.append(df)

# Alle DataFrames zusammenfügen
combined_df = pd.concat(dfs, ignore_index=True)

# Kombinierte Datei speichern
output_file = "/content/drive/MyDrive/Projekt_VIP/Data/pro_vip_usa.csv"
combined_df.to_csv(output_file, index=False)

print(f"Kombinierte Datei gespeichert unter: {output_file}")

Kombinierte Datei gespeichert unter: /content/drive/MyDrive/Projekt_VIP/Data/pro_vip_usa.csv

In [ ]:
len(combined_df)

170134

# Join Germany

In [ ]:
# Pfad zum Hauptordner
main_folder_path = "/content/drive/MyDrive/Projekt_VIP/Data/Germany"

# Liste, um alle DataFrames zu sammeln
dfs = []

# Alle CSV-Dateien im Ordner iterieren
for file in os.listdir(main_folder_path):
    if file.endswith(".csv"):
        file_path = os.path.join(main_folder_path, file)

        # Den Dateinamen ohne Endung extrahieren
        file_name = os.path.splitext(file)[0]

        # CSV-Datei lesen
        df = pd.read_csv(file_path, sep = ";")

        # Spalte mit dem Dateinamen hinzufügen
        df["SourceFile"] = file_name

        # DataFrame zur Liste hinzufügen
        dfs.append(df)

# Alle DataFrames zusammenfügen
combined_df = pd.concat(dfs, ignore_index=True)

# Kombinierte Datei speichern
output_file = "/content/drive/MyDrive/Projekt_VIP/Data/pro_vip_ger.csv"
combined_df.to_csv(output_file, index=False)

print(f"Kombinierte Datei gespeichert unter: {output_file}")

Kombinierte Datei gespeichert unter: /content/drive/MyDrive/Projekt_VIP/Data/pro_vip_ger.csv

# Erstellung stratifiziertes Evaluationssample

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Sharing/Data_BTW/data_btw_final.csv')

In [ ]:
df

,id,id_scraping,post_source_domain,author,author_fullname,timestamp,unix_timestamp,type,url,body,...,residence,job,state,party,list_position,electoral_district_number,job_group,electoral_district_name,acc_type,acc_name
0,DGaimNLImWU,738,https://www.instagram.com/aniko_teamwunderkerze/,aniko_teamwunderkerze,Anikó Glogowski-Merten,2025-02-23T12:05:38Z,1740312338,photo,https://www.instagram.com/p/DGaimNLImWU,Für die Freiheit ❌❌💛✨✅,...,Braunschweig,"MdB, Kunstwissenschaftlerin",NI,FDP,22.0,50.0,71.0,Braunschweig,candidate,aniko_teamwunderkerze
1,DGXwCDoogzO,738,https://www.instagram.com/aniko_teamwunderkerze/,aniko_teamwunderkerze,Anikó Glogowski-Merten,2025-02-22T10:05:00Z,1740218700,photo,https://www.instagram.com/p/DGXwCDoogzO,"Ihr Lieben, morgen ist Wahl und ich hoffe ihr ...",...,Braunschweig,"MdB, Kunstwissenschaftlerin",NI,FDP,22.0,50.0,71.0,Braunschweig,candidate,aniko_teamwunderkerze
2,DGVdlrJIJ6a,738,https://www.instagram.com/aniko_teamwunderkerze/,aniko_teamwunderkerze,Anikó Glogowski-Merten,2025-02-21T12:45:00Z,1740141900,photo,https://www.instagram.com/p/DGVdlrJIJ6a,Weil du es dir irgendwann ja auch mal gewünsch...,...,Braunschweig,"MdB, Kunstwissenschaftlerin",NI,FDP,22.0,50.0,71.0,Braunschweig,candidate,aniko_teamwunderkerze
3,DGSj2FHoVsj,738,https://www.instagram.com/aniko_teamwunderkerze/,aniko_teamwunderkerze,Anikó Glogowski-Merten,2025-02-20T09:42:36Z,1740044556,photo,https://www.instagram.com/p/DGSj2FHoVsj,"Móin ✨ Es ist Zeit, dass Selbstständige und Gr...",...,Braunschweig,"MdB, Kunstwissenschaftlerin",NI,FDP,22.0,50.0,71.0,Braunschweig,candidate,aniko_teamwunderkerze
4,DGNomEqoNmJ,738,https://www.instagram.com/aniko_teamwunderkerze/,aniko_teamwunderkerze,Anikó Glogowski-Merten,2025-02-18T11:47:55Z,1739879275,photo,https://www.instagram.com/p/DGNomEqoNmJ,Verhandlungen über den Frieden in Europa darf ...,...,Braunschweig,"MdB, Kunstwissenschaftlerin",NI,FDP,22.0,50.0,71.0,Braunschweig,candidate,aniko_teamwunderkerze
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149974,DCV3cZStZy8,678,https://www.instagram.com/dirk_brandes/,dirk_brandes,Dirk Brandes,2024-11-14T06:26:00Z,1731565560,photo,https://www.instagram.com/p/DCV3cZStZy8,Ein grandioser Abend!\n\nVielen Dank für den w...,...,Wedemark,"MdB, Industriekaufmann",NI,AfD,1.0,43.0,71.0,Hannover-Land I,candidate,dirk_brandes
149975,DCJmEeGtlJw,678,https://www.instagram.com/dirk_brandes/,dirk_brandes,Dirk Brandes,2024-11-09T12:03:59Z,1731153839,video,https://www.instagram.com/p/DCJmEeGtlJw,Die Ampel hat fertig! 🚦,...,Wedemark,"MdB, Industriekaufmann",NI,AfD,1.0,43.0,71.0,Hannover-Land I,candidate,dirk_brandes
149976,DCGrA3CN6-e,678,https://www.instagram.com/dirk_brandes/,dirk_brandes,Dirk Brandes,2024-11-08T08:56:36Z,1731056196,video,https://www.instagram.com/p/DCGrA3CN6-e,NaN,...,Wedemark,"MdB, Industriekaufmann",NI,AfD,1.0,43.0,71.0,Hannover-Land I,candidate,dirk_brandes
149977,DCCLB8uNIm8,678,https://www.instagram.com/dirk_brandes/,dirk_brandes,Dirk Brandes,2024-11-06T14:53:52Z,1730904832,video,https://www.instagram.com/p/DCCLB8uNIm8,"Herzlichen Glückwunsch, #Trump!",...,Wedemark,"MdB, Industriekaufmann",NI,AfD,1.0,43.0,71.0,Hannover-Land I,candidate,dirk_brandes
149978,DCBcmvtNh2j,678,https://www.instagram.com/dirk_brandes/,dirk_brandes,Dirk Brandes,2024-11-06T08:06:41Z,1730880401,photo,https://www.instagram.com/p/DCBcmvtNh2j,Glückwunsch an Robert Preuß! 💙\n\nAm vergangen...,...,Wedemark,"MdB, Industriekaufmann",NI,AfD,1.0,43.0,71.0,Hannover-Land I,candidate,dirk_brandes

In [ ]:
print(df.columns.tolist())
print(sampled_df.columns.tolist())

['id', 'id_scraping', 'post_source_domain', 'author', 'author_fullname', 'timestamp', 'unix_timestamp', 'type', 'url', 'body', 'hashtags', 'likes_hidden', 'num_likes', 'num_comments', 'num_media', 'num_followers', 'interaction_rate', 'location_name', 'location_latlong', 'location_city', 'missing_fields', 'filename_image', 'name', 'surnames', 'sex', 'birth_year', 'postal_code', 'residence', 'job', 'state', 'party', 'list_position', 'electoral_district_number', 'job_group', 'electoral_district_name', 'acc_type', 'acc_name']
['id', 'post_source_domain', 'author', 'author_fullname', 'timestamp', 'unix_timestamp', 'url', 'body', 'hashtags', 'likes_hidden', 'num_likes', 'num_comments', 'num_media', 'num_followers', 'interaction_rate', 'location_name', 'location_latlong', 'location_city', 'missing_fields', 'filename_image', 'name', 'surnames', 'birth_year', 'postal_code', 'residence', 'job', 'list_position', 'electoral_district_number', 'job_group', 'electoral_district_name', 'acc_name']

In [ ]:
df['sex'] = df['sex'].fillna('party')
df['state'] = df['state'].fillna('party')
df['party'] = df['party'].fillna('unknown')

# Gesamtanzahl der Zeilen für das Sample
sample_size = 5000

# Sampling nach "id_scraping", "type", "state" und "party"
sampled_df = (
    df.groupby(['id_scraping', 'type', 'state', 'party', 'acc_type', 'sex'], group_keys=False)
      .apply(lambda x: x.sample(frac=sample_size / len(df), random_state=42))
      .reset_index(drop=True)
)

print(sampled_df.columns)

Index(['id', 'id_scraping', 'post_source_domain', 'author', 'author_fullname',
       'timestamp', 'unix_timestamp', 'type', 'url', 'body', 'hashtags',
       'likes_hidden', 'num_likes', 'num_comments', 'num_media',
       'num_followers', 'interaction_rate', 'location_name',
       'location_latlong', 'location_city', 'missing_fields', 'filename_image',
       'name', 'surnames', 'sex', 'birth_year', 'postal_code', 'residence',
       'job', 'state', 'party', 'list_position', 'electoral_district_number',
       'job_group', 'electoral_district_name', 'acc_type', 'acc_name'],
      dtype='object')

/tmp/ipython-input-3280031080.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(frac=sample_size / len(df), random_state=42))

In [ ]:
sampled_df

,id,id_scraping,post_source_domain,author,author_fullname,timestamp,unix_timestamp,type,url,body,...,residence,job,state,party,list_position,electoral_district_number,job_group,electoral_district_name,acc_type,acc_name
0,DGYw1WugktM,1,https://www.instagram.com/canancanli.cc/,aydincandan47,Aydin Candan,2025-02-22T19:31:33Z,1740252693,photo,https://www.instagram.com/p/DGYw1WugktM,Her oy önemlidir - lütfen herkes gidip oy vers...,...,Kiel,Bankfachwirtin,SH,SPD,10.0,1.0,72.0,Schleswig-Holstein,candidate,canancanli.cc
1,DFzmSGsNHtV,2,https://www.instagram.com/katrin_fedrowitz/,katrin_fedrowitz,Katrin Fedrowitz,2025-02-08T09:07:27Z,1739005647,photo,https://www.instagram.com/p/DFzmSGsNHtV,Wahlkampfstand am Morgen! #friedrichsgabe @ben...,...,Norderstedt,Bürovorsteherin im RA- und Notarfach,SH,SPD,12.0,1.0,71.0,Schleswig-Holstein,candidate,katrin_fedrowitz
2,DFiBS4ZIsy4,2,https://www.instagram.com/katrin_fedrowitz/,katrin_fedrowitz,Katrin Fedrowitz,2025-02-01T13:17:10Z,1738415830,photo,https://www.instagram.com/p/DFiBS4ZIsy4,Das Wochenende startet für mich mit Infostände...,...,Norderstedt,Bürovorsteherin im RA- und Notarfach,SH,SPD,12.0,1.0,71.0,Schleswig-Holstein,candidate,katrin_fedrowitz
3,DDaAP3fMLf5,32,https://www.instagram.com/connyclausen.gruen/,connyclausen.gruen,Conny Clausen,2024-12-10T17:31:18Z,1733851878,photo,https://www.instagram.com/p/DDaAP3fMLf5,"🌱 Liebe Freund*innen,\nich freue mich riesig, ...",...,Flensburg,Mathematikerin,SH,GRÜNE,9.0,1.0,41.0,Schleswig-Holstein,candidate,connyclausen.gruen
4,DGD93b9ocXD,32,https://www.instagram.com/connyclausen.gruen/,grueneflensburg,Grüne Flensburg 🌻 | Kreisverband & Ratsfraktion,2025-02-14T17:46:30Z,1739555190,video,https://www.instagram.com/p/DGD93b9ocXD,Echten Klimaschutz? Gibt es nur mit uns! ✅\n\n...,...,Flensburg,Mathematikerin,SH,GRÜNE,9.0,1.0,41.0,Schleswig-Holstein,candidate,connyclausen.gruen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4754,DCTaMboo4UQ,4959,https://www.instagram.com/mera25.nrw/,johannes.fehr,Johannes Fehr,2024-11-13T07:33:18Z,1731483198,video,https://www.instagram.com/p/DCTaMboo4UQ,"Jetzt bei @mera25.de Mitglied werden, denn die...",...,NaN,NaN,party,MERA25,NaN,NaN,NaN,NaN,party,mera25.nrw
4755,DCKqL_fojRz,4966,https://www.instagram.com/werteunion/,werteunion,WerteUnion,2024-11-09T21:58:32Z,1731189512,photo,https://www.instagram.com/p/DCKqL_fojRz,NaN,...,NaN,NaN,party,WerteUnion,NaN,NaN,NaN,NaN,party,werteunion
4756,DCwg-5coKtC,4966,https://www.instagram.com/werteunion/,werteunion,WerteUnion,2024-11-24T14:49:14Z,1732459754,photo,https://www.instagram.com/p/DCwg-5coKtC,„Die CDU/CSU ist total entkernt!“ - Dr. Jörg U...,...,NaN,NaN,party,WerteUnion,NaN,NaN,NaN,NaN,party,werteunion
4757,DFlcWt5Nj2_,4975,https://www.instagram.com/werteunionnds/,werteunionnds,WerteUnion Niedersachsen,2025-02-02T21:11:33Z,1738530693,video,https://www.instagram.com/p/DFlcWt5Nj2_,Grüne Doppelmoral…. Wenn die Grünen eines zuve...,...,NaN,NaN,party,WerteUnion,NaN,NaN,NaN,NaN,party,werteunionnds
4758,DC95o15NNS_,4975,https://www.instagram.com/werteunionnds/,werteunionnds,WerteUnion Niedersachsen,2024-11-29T19:37:34Z,1732909054,video,https://www.instagram.com/p/DC95o15NNS_,Grenzüberschreitende Sprache: Indem der @die_g...,...,NaN,NaN,party,WerteUnion,NaN,NaN,NaN,NaN,party,werteunionnds

In [ ]:
# Verteilung im Original-Datensatz nach "SourceFile" und "type"
original_distribution = (
    df.groupby(['id_scraping', 'type', 'state', 'party', 'acc_type', 'sex']).size() / len(df)
)

# Verteilung im Sample nach "SourceFile" und "type"
sampled_distribution = (
    sampled_df.groupby(['id_scraping', 'type', 'state', 'party', 'acc_type', 'sex']).size() / len(sampled_df)
)

# Vergleich ausgeben
print("Original-Verteilung:\n", original_distribution)
print("Sample-Verteilung:\n", sampled_distribution)

# Überprüfen, ob die Verteilungen ähnlich sind
comparison = pd.concat([original_distribution, sampled_distribution], axis=1, keys=['Original', 'Sample'])
comparison

Original-Verteilung:
 id_scraping  type   state  party       acc_type   sex
1            mixed  SH     SPD         candidate  w        0.000013
             photo  SH     SPD         candidate  w        0.000133
             video  SH     SPD         candidate  w        0.000020
2            photo  SH     SPD         candidate  w        0.000387
             video  SH     SPD         candidate  w        0.000040
                                                             ...
4974         photo  party  WerteUnion  party      party    0.000053
4975         photo  party  WerteUnion  party      party    0.000013
             video  party  WerteUnion  party      party    0.000333
4980         photo  party  WerteUnion  party      party    0.000040
4981         photo  party  WerteUnion  party      party    0.000020
Length: 5901, dtype: float64
Sample-Verteilung:
 id_scraping  type   state  party       acc_type   sex
1            photo  SH     SPD         candidate  w        0.000210
2            photo  SH     SPD         candidate  w        0.000420
32           photo  SH     GRÜNE       candidate  w        0.000210
             video  SH     GRÜNE       candidate  w        0.000210
34           photo  SH     GRÜNE       candidate  m        0.000210
                                                             ...
4956         photo  party  MERA25      party      party    0.000420
4959         photo  party  MERA25      party      party    0.000841
             video  party  MERA25      party      party    0.000420
4966         photo  party  WerteUnion  party      party    0.000420
4975         video  party  WerteUnion  party      party    0.000420
Length: 2731, dtype: float64

                                                    Original   Sample
id_scraping type  state party      acc_type  sex
1           mixed SH    SPD        candidate w      0.000013      NaN
            photo SH    SPD        candidate w      0.000133  0.00021
            video SH    SPD        candidate w      0.000020      NaN
2           photo SH    SPD        candidate w      0.000387  0.00042
            video SH    SPD        candidate w      0.000040      NaN
...                                                      ...      ...
4974        photo party WerteUnion party     party  0.000053      NaN
4975        photo party WerteUnion party     party  0.000013      NaN
            video party WerteUnion party     party  0.000333  0.00042
4980        photo party WerteUnion party     party  0.000040      NaN
4981        photo party WerteUnion party     party  0.000020      NaN

[5901 rows x 2 columns]

In [ ]:
output_file = "/content/drive/MyDrive/Projekt_VIP/Data/Eva/POL/pro_vip_eva_pol.csv"
sampled_df.to_csv(output_file, index=False)

# Eva-Learn-Split

## VIP

In [ ]:
import pandas as pd
from sklearn.model_selection import StratifiedKFold

# Datensatz einlesen
df = pd.read_csv('/content/drive/MyDrive/Projekt_VIP/Data/Eva/USA/eva_usa_anno.csv', sep=";")

# Anzahl der Folds
k = 5

# Stratified K-Fold Initialisierung (nach "SourceFile" und "type" stratifiziert)
skf = StratifiedKFold(n_splits=k, shuffle=True, random_state=42)

# Sicherstellen, dass die Stratifizierung korrekt funktioniert
y = df[['SourceFile', 'type']].astype(str).agg('-'.join, axis=1)  # Kombination beider Spalten für die Stratifizierung

# K-Fold Split durchführen
for i, (train_idx, val_idx) in enumerate(skf.split(df, y)):
    train_df = df.iloc[train_idx]
    val_df = df.iloc[val_idx]

    # Speichern der CSV-Dateien für diesen Fold
    train_df.to_csv(f'/content/drive/MyDrive/Projekt_VIP/Data/Eva/USA/val_df_usa_{i+1}.csv', index=False, sep=";")
    val_df.to_csv(f'/content/drive/MyDrive/Projekt_VIP/Data/Eva/USA/learn_df_usa_{i+1}.csv', index=False, sep=";")

    print(f"Fold {i+1}: Val Size = {len(train_df)}, Learn Size = {len(val_df)}")

print("Stratifizierte K-Fold Cross-Validation abgeschlossen.")

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

Fold 1: Val Size = 7584, Learn Size = 1896
Fold 2: Val Size = 7584, Learn Size = 1896
Fold 3: Val Size = 7584, Learn Size = 1896
Fold 4: Val Size = 7584, Learn Size = 1896
Fold 5: Val Size = 7584, Learn Size = 1896
Stratifizierte K-Fold Cross-Validation abgeschlossen.

In [ ]:
import pandas as pd

# CSV-Datei einlesen
csv_file = "/content/drive/MyDrive/Projekt_VIP/Data/Class/USA/full_dataset.csv"
df = pd.read_csv(csv_file)  # Falls das Trennzeichen anders ist, anpassen

# XLSX-Datei speichern
xlsx_file = "/content/drive/MyDrive/Projekt_VIP/Data/Class/USA/full_dataset.xlsx"
df.to_excel(xlsx_file, index=False, sheet_name="Daten")  # index=False, um keine unnötige Indexspalte zu speichern

print(f"Datei erfolgreich gespeichert unter: {xlsx_file}")

<ipython-input-2-94d5dd1fd233>:5: DtypeWarning: Columns (19,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_file)  # Falls das Trennzeichen anders ist, anpassen

Datei erfolgreich gespeichert unter: /content/drive/MyDrive/Projekt_VIP/Data/Class/USA/full_dataset.xlsx

## POL

In [ ]:
import pandas as pd
from sklearn.model_selection import StratifiedKFold

# Datensatz einlesen
df = pd.read_csv('/content/drive/MyDrive/Projekt_VIP/Data/POL/pro_vip_eva_pol.csv', sep=";")

# Anzahl der Folds
k = 5

# Stratified K-Fold Initialisierung (nach "id_scraping" und "type" stratifiziert)
skf = StratifiedKFold(n_splits=k, shuffle=True, random_state=42)

# Sicherstellen, dass die Stratifizierung korrekt funktioniert
y = df[['id_scraping', 'type']].astype(str).agg('-'.join, axis=1)  # Kombination beider Spalten für die Stratifizierung

# K-Fold Split durchführen
for i, (train_idx, val_idx) in enumerate(skf.split(df, y)):
    train_df = df.iloc[train_idx]
    val_df = df.iloc[val_idx]

    # Speichern der CSV-Dateien für diesen Fold
    train_df.to_csv(f'/content/drive/MyDrive/Projekt_VIP/Data/POL/val_df_pol_{i+1}.csv', index=False, sep=";")
    val_df.to_csv(f'/content/drive/MyDrive/Projekt_VIP/Data/POL/learn_pol_usa_{i+1}.csv', index=False, sep=";")

    print(f"Fold {i+1}: Val Size = {len(train_df)}, Learn Size = {len(val_df)}")

print("Stratifizierte K-Fold Cross-Validation abgeschlossen.")

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

Fold 1: Val Size = 3810, Learn Size = 953
Fold 2: Val Size = 3810, Learn Size = 953
Fold 3: Val Size = 3810, Learn Size = 953
Fold 4: Val Size = 3811, Learn Size = 952
Fold 5: Val Size = 3811, Learn Size = 952
Stratifizierte K-Fold Cross-Validation abgeschlossen.